version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    environment:
      GRADLE_OPTS: -Dorg.gradle.workers.max=1 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy="in-process"
    steps:
      - checkout
      - run:
          name: Make gradlew executable
          command: chmod +x ./gradlew
      - run:
          name: Clean
          command: ./gradlew clean & find buildSrc -type f -name "*.lock" -delete
      - run:
          name: Build
          command: ./gradlew --parallel app:assembleOnlineRelease