GROUP=io.github.goooler.android
POM_ARTIFACT_ID=adapter-vp
VERSION_NAME=1.0.0

POM_URL=https://github.com/Goooler/DemoApp
POM_SCM_URL=https://github.com/Goooler/DemoApp/
POM_SCM_CONNECTION=scm:git:git://github.com/Goooler/DemoApp.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/Goooler/DemoApp.git

POM_LICENCE_NAME=The Apache Software License, Version 2.0
POM_LICENCE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENCE_DIST=repo

POM_DEVELOPER_ID=Goooler
POM_DEVELOPER_NAME=Zongle Wang

SONATYPE_HOST=S01
