name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Github Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 20
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew app:assembleProdRelease
      - uses: ncipollo/release-action@v1
        with:
          artifacts: app/build/outputs/apk/prod/release/*.apk
          token: ${{ secrets.GITHUB_TOKEN }}
